### ISSUE TITLE
Music Player Buttons

### ISSUE THREAD

**Issue by annaspri** [es1294/AirMusic#105]
Add the following buttons (with corresponding functionality) to the music player page:
- Play
- Pause 
- Previous Track
- Next Track

**Comment by annaspri** [comment]
Closed with commit fd5279729d739d1839fa24a7efa745436a8766b2

**Comment by sohamdes** [comment]
Acceptance Test-

Play Button- Press the 'play' button to start playing the song.
Pause Button- Press the 'pause' button to pause the song.
Next Button- Press the 'next' button to skip to the next song in the list.
Previous Button- Press the 'previous' button to skip to the previous song in the list.

When the 'play' button is pressed, it changes the image to the 'pause' button.
When the 'pause' button is pressed, it changes the image to the 'play' button.
