### ISSUE TITLE
Task: Feed GUI

### ISSUE THREAD

**Issue by annaspri** [es1294/AirMusic#11]
Create the basic GUI for the feed page.

**Comment by mahiaash** [comment]
Testing for Feed page
- When clicking on the menu page and then clicking on Feed item it leads to the feed page.
- First thing should show is a list of friends photos, names and the current song they are listening to as well as the artist of the song. 
- To see the rest of the friends the page should be able to scroll down. To know if this worked or not loading animation will occur and the first picture will disappear
- You can click on the friends currently in the list. To know if they have been clicked a message will appear with the message "You clicked on: <insert friend that you clicked here>" that is how you know it worked
