### ISSUE TITLE
User Story #2: View Feed

### ISSUE THREAD

**Issue by sohamdes** [es1294/AirMusic#2]
As a listener, I want to view the feed in order to see what my friends are listening to.

**Comment by sohamdes** [comment]
Acceptance Test-
-Open the app and Login.
-Navigate to the Feed page using the menu button on top right corner. 
-The Feed page should list the users in the database.(Does not show what song the users are listening to yet).

**Comment by annaspri** [comment]
Closed within merge  ae02310da0b8a04befe64453e27b1974e406cbe3
