### ISSUE TITLE
User Story #4: Joining Sessions

### ISSUE THREAD

**Issue by sohamdes** [es1294/AirMusic#4]
As a friend of the user I want to join his session so I can listen to what he is listening to.

**Comment by sohamdes** [comment]
Acceptance Test-
Open the app and Login.
Navigate to the Feed page from the menu button.
You should see a list of users that are in the database.
Click on the user that you want to listen to songs with.
Music page should open and start playing the song from the beginning.
If the user is not online, a message should appear saying "Nothing to listen to!".

**Comment by annaspri** [comment]
Closed with merge of musicWorkaround branch in merge ae02310da0b8a04befe64453e27b1974e406cbe3
