### ISSUE TITLE
User Story #12: Listening to music

### ISSUE THREAD

**Issue by annaspri** [es1294/AirMusic#52]
As a user, I want to select a song from the app so that I can listen to it.

**Comment by mahiaash** [comment]
### Acceptance Test
Test 1. Playing Music 
1. In the music page, when play button is pressed, it plays the current song.
         a. When the song is playing, the play icon changes to pause icon. 
         b.  When the song is paused, the pause icon changes to play icon.
2. When next button is pressed, the next song is played. 
3. When the previous button is pressed, the previous song is played.
4. When the app is closed or the page is changed, the current song does not stop playing
Test 2. Air Music Logo
  1. On the music page, if log is touched 
       Expected result: A message will pop up telling you that you are already on the music page.
  2. On any other page, if logo is touched 
     Expected music page with current song is displayed
3. first logged in and logo is tapped
    Expected music page opens and a random song from song list is played
Test 3. Sliders
1. when volume slider is changed the volume of song increases / decreases with it
2. When the seek bar is changed, the current song plays at the seek bar.
3. When the seek bar is changed, the time labels are also updated to the corresponding  times. 
Test 4.  Songs
1. Navigate to the Songs from the menu.
     Expected Result: A list of songs in the app should appear.
2. Tap on any song.
     Expected Result: The page changes to Music page and the selected song starts to play.
