### ISSUE TITLE
User Story #8: Editing Profile

### ISSUE THREAD

**Issue by sohamdes** [es1294/AirMusic#8]
As a listener, I want to upload a profile picture and favorite songs so I can share my it with friends.

**Comment by annaspri** [comment]
Story completed in Profile_Database_Expansions branch c96546719d15679e5af71c09859d7768b3ee164e

**Comment by annaspri** [comment]
Re-opening because we need to incorporate functionality with a server.

**Comment by annaspri** [comment]
Closed with merge 1b19d797afbf22d073276611e850338f03ea8208

**Comment by annaspri** [comment]
**Acceptance Test**

**Script**
1. Click the "edit profile" button on your profile page. You will be taken to the edit form.
2. Make as many changes as you want!
3. Choose a photo from your phone's gallery by clicking the "change profile photo" button at the bottom of the form. 
4. Once you have made your changes, touch the "save changes" button.

All of your information has been updated.
